### ISSUE TITLE
Add manage mobile numbers

### ISSUE THREAD

**Issue by Helghardt** [rehive/wallet-ionic#12]
1. First phone number is set as primary.
2. Set any phone number to primary.
3. Delete existing phone numbers.
4. Verify each phone number.
5. Resend verification code.
6. Claim outstanding transactions for each mobile number that is verified.
7. Allow user to delete non-primary number and add to another account. Do not claim money again.

**Comment by OdinsPlasmaRifle** [comment]
Regarding point (6): this is already working as requested.

**Comment by OdinsPlasmaRifle** [comment]
Requirements 1 -7 have all been completed. Verification is handled via an OTP sent when a number is added or upon registration. The OTP can be resent, at which point the OTP form is displayed to a user again.

Transaction "claims" are only run once, and will only every apply to a single user. So deleting a mobile number and using it elsewhere will not rerun claims on the new account.
